### ISSUE TITLE
why am i getting my local computer and IP ADDRESS in the mail that sent 

### ISSUE THREAD

**Issue by aviado1** [Darkseal/RunningLow#2] opened 2020-11-17 14:51 UTC
why am i getting my local computer and IP ADDRESS in the mail that sent ?
i'm testing 2 machines
  [string] $hosts = "aviado-dell:NDC",
  $volumes = "C:D"

the reasult is wrong 
comes with my computer:

Hello there, 

this is an automatic e-mail message sent by RunningLow Powershell script to inform you that **AVIADO-PC** drive D is running low on free space.

**Comment by Death259** [comment] 2021-06-09 12:58
I know this is an old comment at this point, but I started using this as well and ran across the same issue. The problem is that the portion that sends the email out is looking at the computer that the script is currently running on. I have fixed that and created a Pull Request to get the code fixed in this project as well. Please see #4 for the changes that need to be made for it to work.

**Comment by Darkseal** [comment] 2021-06-09 14:22
Merged #4

**Closed as completed by Darkseal** 2021-06-09 14:22 UTC
